# Configuration for Travis-CI

language: java

# For enabling the generation of the native executables
sudo: required

matrix:
  fast_finish: true
  include:

    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
          - xvfb
          - lib32z1
          - lib32ncurses5
          - genisoimage
      before_install:
      - "sh -e ./build-tools/scripts/travis-download-maven.sh"
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx3g\"" > $HOME/.mavenrc
      env: DISPLAY=:99.0

    - os: osx
      osx_image: xcode8.2 # see https://docs.travis-ci.com/user/osx-ci-environment/
      before_install:
      - mvn -Xmx32m --version
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx3g\"" > $HOME/.mavenrc

install: true

script: "mvn -B -e -P!generateproduct clean install"

#after_failure: "sh -e ./build-tools/scripts/print-surefire-reports.sh"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.binaries

env:
  global:
    - secure: "e+S71qmexycXKKiRLzc/B12HO64XiGxB9nWW5vifuOI22qjsma6T2z4z+v5qWgSG0O5SEHjQCw+rXDjoqjD0hA8qHpiaFb5vuKS69ulBFfTM5QT4+5F3RX/xepYfrUZlAner7ES7UrYnwDOlASrARiy1HLmcWHcruLosWWgev9Y="
    - secure: "grzZIv0E+OjSYyB81LH9j2KjH2SCspvsRY54KXD0dP7QmFb8pNbWClhV0TpGevaU4uocDn2ZhlXQdCEpzpesHo0LcPKz+b03xPg6ydbXvMuFXzJ4fFEUfi5iaRGuDDIFm/IPGEMRYyv62poUMFiKpwgECvFjE4ECG8NPegpZnz8="
    - secure: "aIOrF7Oa3r2ZWuRC6YwSuw1UnDoBLz8uLjNmtq3ZIJzukI93NfjmnJcr+d278nvqOWm/eR+UPkE8fB8PgWamAoxYRK60bjP9ScvaudqR4cztwKMzHLetR1+h0yt3qRS3sl2ImdY2k0UkZDLe+sW7ColCnC1pKM4ty9mbs2tBbvk="
    - secure: "SIQFWoeSvpHTtWi9x8SZ7J2qDU7OspParyQLAMuKsOK/SMeRbSEGoz1GMgoGMkTsrV64jbG82FTp+0h1ja4ImiaqNuJU7nnIya1CXQOQdtt2q0kcnVBUwhjNoASbxNdScFYrFRIv6205PlolehhpNl52YK5v1Lk0fdfxCaYaxsY="

# Deployment of the SNAPSHOT version.
after_success:
  - "[[ ${TRAVIS_OS_NAME} == 'linux' ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && [[ ${TRAVIS_BRANCH} == 'master' ]] && mvn -B deploy -DskipTests -Dmaven.test.skip=true -Dcheckstyle.skip=true --settings build-tools/src/main/resources/maven/deploy-settings.xml"


